final_updated/website/models.py
from . import db
from flask_login import UserMixin


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    name = db.Column(db.String(150))
    role = db.Column(db.String(50), nullable=False)
    
    def __repr__(self):
        return f'<User {self.email}>'

final_updated/website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager
import os

basedir = os.path.abspath(os.path.dirname(__file__))

db = SQLAlchemy()
DB_NAME = "database.db"


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'hello'
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + os.path.join(basedir, DB_NAME)
    db.init_app(app)

    from .auth import auth
    from .views import main
    app.register_blueprint(auth, url_prefix='/')
    app.register_blueprint(main, url_prefix='/')

    from .models import User
    
    with app.app_context():
        db.create_all()

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app

final_updated/website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_user, login_required, current_user, logout_user
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db   

auth = Blueprint('auth', __name__)

# hospital login and signup

@auth.route('/login-h', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.hospital_dashboard_View'))
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('main.hospital_dashboard_View'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("loginH.html")


@auth.route('/sign-up-h', methods=['GET', 'POST'])
def sign_up():
    if current_user.is_authenticated:
        return redirect(url_for('main.hospital_dashboard_View'))
    if request.method == 'POST':
        email = request.form.get('email')
        name = request.form.get('name')
        password = request.form.get('password')

        if len(email) < 5:
            flash('Email must be at least 5 characters.', category='error')
        elif len(name) < 2:
            flash('First name must be at least 2 characters.', category='error')
        elif len(password) < 6:
            flash('Password must be at least 6 characters.', category='error')
        else:
            user = User.query.filter_by(email=email).first()
            if user:
                flash('Email already exists.', category='error')
            else:
                new_user = User(email=email, name=name, password=generate_password_hash(password),role="hospital")
                db.session.add(new_user)
                db.session.commit()
                login_user(new_user, remember=True)
                flash('Account created!', category='success')
                return redirect(url_for('main.hospital_dashboard_View'))
    
    return render_template("signupH.html")


# login and signup for patient


@auth.route('/sign-up-p', methods=['GET', 'POST'])
def sign_up_patient():
    if current_user.is_authenticated:
        return redirect(url_for('main.patient_dashboard_View'))
    if request.method == 'POST':
        email = request.form.get('email')
        name = request.form.get('name')
        password = request.form.get('password')

        if len(email) < 5:
            flash('Email must be at least 5 characters.', category='error')
        elif len(name) < 2:
            flash('First name must be at least 2 characters.', category='error')
        elif len(password) < 6:
            flash('Password must be at least 6 characters.', category='error')
        else:
            user = User.query.filter_by(email=email).first()
            if user:
                flash('Email already exists.', category='error')
            else:
                new_user = User(email=email, name=name, password=generate_password_hash(password),role="patient")
                db.session.add(new_user)
                db.session.commit()
                login_user(new_user, remember=True)
                flash('Account created!', category='success')
                return redirect(url_for('main.patient_dashboard_View'))
    
    return render_template("signupP.html")


@auth.route('/login-p', methods=['GET', 'POST'])
def login_patient():
    if current_user.is_authenticated:
        return redirect(url_for('main.patient_dashboard_View'))
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('main.patient_dashboard_View'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("loginP.html")


# logout for both hospital and patient

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Logout successful!', category='success')
    return redirect(url_for('main.index_View'))

final_updated/website/views.py
from flask import Blueprint, render_template
from .permissions import role_required

main = Blueprint('main', __name__)


@main.route('/')
def index_View():
    return render_template("main_page_ds.html")


# hospital views

@main.route('/dashboard-h')
@role_required('hospital')
def hospital_dashboard_View():
    return render_template("dashboardH.html")

@main.route('/appointment-h')
@role_required('hospital')
def hospital_appointment_View():
    return render_template("appointmentsH.html")

@main.route('/records-h')
@role_required('hospital')
def hospital_records_View():
    return render_template("recordsH.html")

@main.route('/lens-h')
@role_required('hospital')
def hospital_lens_View():
    return render_template("lensH.html")


# patient views

@main.route('/dashboard-p')
@role_required('patient')
def patient_dashboard_View():
    return render_template("dashboardP.html")


@main.route('/appointment-p')
@role_required('patient')
def patient_appointment_View():
    return render_template("appointmentsP.html")

@main.route('/profile-p')
@role_required('patient')
def patient_profile_View():
    return render_template("profileP.html")

final_updated/website/templates/includes/messages.html
<style>
    /* CSS styles for flash messages */
    .success {
        color: green;
    }
    
    .error {
        color: red;
    }
    
    .info {
        color: blue;
    }
    
    .flashes {
        list-style-type: none;
        padding: 0;
    }
    
    .flash {
        margin-bottom: 10px;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
    }
</style>


{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    <div class="flashes">
    {% for category, message in messages %}
      <div class="flash {{ category }}">{{ message }}</div>
    {% endfor %}
    </div>
  {% endif %}
{% endwith %}

<script>
   
    setTimeout(function() {
        var flashes = document.querySelectorAll('.flash');
        flashes.forEach(function(flash) {
            flash.style.display = 'none';
        });
    }, 2000);
</script>

final_updated/website/templates/includes/sidemenu-hospital.html
<ul>
    <li><a href="{{url_for('main.hospital_dashboard_View')}}">Dashboard</a></li>
    <br>
    <li><a href="{{url_for('main.hospital_appointment_View')}}">Upcoming Appointments</a></li>
    <br>
    <li><a href="{{url_for('main.hospital_records_View')}}">Patient Records</a></li>
    <br>
    <li><a href="{{url_for('main.hospital_lens_View')}}">Lens</a></li>
    <br>
    <li><a href="{{url_for('auth.logout')}}">Log out</a></li>
</ul>

final_updated/website/templates/includes/sidemenu-patient.html
<ul>
    <li><a href="{{url_for('main.patient_dashboard_View')}}">Dashboard</a></li>
    <br>
    <li><a href="{{url_for('main.patient_appointment_View')}}">Upcoming Appointments</a></li>
    <br>
    <li><a href="{{url_for('main.patient_profile_View')}}">Profile</a></li>
    <br>
    <li><a href="{{url_for('auth.logout')}}">Log out</a></li>
</ul>

final_updated/website/templates/loginH.html
<!-- log in p4 -->
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Signup</title>
    <style>
        body{
            background-color: #f9f9f9;
        }
        .container {
            position: relative;
            width: 450px;
            margin: 20px;
            padding: 20px;
            background-color: #ffffff;
            border-radius: 10px;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
            float: left; /* Move container to the left */
        }
        .background-image {
            position: absolute;
            top: 0;
            right: 0;
            bottom: 0;
            left: 68%; /* Move background image to the right */
            background-image: url('signup.jpeg');
            background-size: contain;
            z-index: -1; /* Ensure background image is behind other content */
        }
        h1 {
            text-align: center;
            color: #333;
        }
        .signup-form {
            display: flex;
            flex-direction: column;
        }
        .signup-form input {
            margin-bottom: 20px;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
            font-size: 16px;
        }
        .signup-form button {
            padding: 10px;
            border: none;
            border-radius: 4px;
            font-size: 16px;
            cursor: pointer;
            background-color: #99C1D6;
            color: #fff;
        }
        .signup-form button:hover {
            background-color: #0056b3;
        }
        .signup-form .social-login {
            margin-top: 20px;
            text-align: center;
        }
        .signup-form .social-login button {
            margin-top: 10px;
            background-color: #99C1D6; /* Facebook blue */
        }
        .signup-form .social-login button.google {
            background-color: #db4437; /* Google red */
        }
        .center{
            text-align: center;
        }
        h2{
            color: #a09e9e;
            font-size: medium;
        }
        h3{
            color: black;
            font-size: medium;
            font-family:Arial, Helvetica, sans-serif;
        }
        .button {
            background-color: #99C1D6; /* White background color for the button */
            color: #ffffff; /* Blue text color for the button */
            border: none; /* Remove button border */
            padding: 10px 20px; /* Add padding to the button */
            font-size: 16px; /* Set font size */
            border-radius: 5px; /* Add rounded corners to the button */
            cursor: pointer; /* Change cursor to pointer on hover */
            transition: background-color 0.3s, color 0.3s; /* Add smooth transition for hover effect */
            text-decoration: none; /* Remove default link underline */
            text-align: center;
        }
        .button:hover {
            background-color: #ffffff; /* Darker blue background color on hover */
            color: #99C1D6; /* White text color on hover */
        }
    </style>
</head>

<body>
    {% include "includes/messages.html" %}
    <div class="container">
        <h1>Log In</h1>
        <h3>Dont have an Account <a href="{{url_for('auth.sign_up')}}"> Sign Up</a></h3>
        <form class="signup-form" action="{{url_for('auth.login')}}" method="POST">
            <h2>Email Address</h2>
            <input type="email" placeholder="Email Address" name="email" required>
            <h2>Password</h2>
            <input type="password" placeholder="Enter Password" name="password" required>
            <input type="submit" value="Login" class="button">
        </form>
        <div class="social-login center">
            <p>------ Or Sign In using ------</p>
            <button class="google">Sign In with Google</button>
            <button class="facebook">Sign In with Facebook</button>
        </div>
    </div>
    <div class="background-image"></div> <!-- Background image -->
</body>
</html>

final_updated/website/templates/loginP.html
<!-- log in p4 -->
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Signup</title>
    <style>
        body{
            background-color: #f9f9f9;
        }
        .container {
            position: relative;
            width: 450px;
            margin: 20px;
            padding: 20px;
            background-color: #ffffff;
            border-radius: 10px;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
            float: left; /* Move container to the left */
        }
        .background-image {
            position: absolute;
            top: 0;
            right: 0;
            bottom: 0;
            left: 68%; /* Move background image to the right */
            background-image: url('signup.jpeg');
            background-size: contain;
            z-index: -1; /* Ensure background image is behind other content */
        }
        h1 {
            text-align: center;
            color: #333;
        }
        .signup-form {
            display: flex;
            flex-direction: column;
        }
        .signup-form input {
            margin-bottom: 20px;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
            font-size: 16px;
        }
        .signup-form button {
            padding: 10px;
            border: none;
            border-radius: 4px;
            font-size: 16px;
            cursor: pointer;
            background-color: #99C1D6;
            color: #fff;
        }
        .signup-form button:hover {
            background-color: #0056b3;
        }
        .signup-form .social-login {
            margin-top: 20px;
            text-align: center;
        }
        .signup-form .social-login button {
            margin-top: 10px;
            background-color: #99C1D6; /* Facebook blue */
        }
        .signup-form .social-login button.google {
            background-color: #db4437; /* Google red */
        }
        .center{
            text-align: center;
        }
        h2{
            color: #a09e9e;
            font-size: medium;
        }
        h3{
            color: black;
            font-size: medium;
            font-family:Arial, Helvetica, sans-serif;
        }
        .button {
            background-color: #99C1D6; /* White background color for the button */
            color: #ffffff; /* Blue text color for the button */
            border: none; /* Remove button border */
            padding: 10px 20px; /* Add padding to the button */
            font-size: 16px; /* Set font size */
            border-radius: 5px; /* Add rounded corners to the button */
            cursor: pointer; /* Change cursor to pointer on hover */
            transition: background-color 0.3s, color 0.3s; /* Add smooth transition for hover effect */
            text-decoration: none; /* Remove default link underline */
            text-align: center;
        }
        .button:hover {
            background-color: #ffffff; /* Darker blue background color on hover */
            color: #99C1D6; /* White text color on hover */
        }
    </style>
</head>

<body>
    {% include "includes/messages.html" %}
    <div class="container">
        <h1>Log In</h1>
        <h3>Dont have an Account <a href="{{url_for('auth.sign_up_patient')}}"> Sign Up</a></h3>
        <form class="signup-form" action="{{url_for('auth.login_patient')}}" method="POST">
            <h2>Email Address</h2>
            <input type="email" placeholder="Email Address" name="email" required>
            <h2>Password</h2>
            <input type="password" placeholder="Enter Password" name="password" required>
            <input type="submit" value="Login" class="button">
        </form>
        <div class="social-login center">
            <p>------ Or sign in using ------</p>
            <button class="google">Sign In with Google</button>
            <button class="facebook">Sign In with Facebook</button>
        </div>
    </div>
    <div class="background-image"></div> <!-- Background image -->
</body>
</html>

final_updated/website/templates/main_page_ds.html
<!-- data science front-end p1 -->
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>
            VisionFit
        </title>

        <style>
            body {
                background-image: url('bg1.jpeg');
                /* You can specify additional background properties like size, position, etc. */
            }
            .rectangle {
                width: 110px; /* Width of the rectangle */
                height: 20px; /* Height of the rectangle */
                background-color: #f0f0f0; /* Background color of the rectangle */
                border: 1px solid #000000; /* Border properties of the rectangle */
                padding: 20px; /* Padding inside the rectangle */
                text-align: center; /* Center align the text */
                font-family: Arial, sans-serif; /* Font family for the text */
            }
            .wrectangle {
                width: 100%; /* Width of the rectangle */
                height: 60px; /* Height of the rectangle */
                background-color: #f0f0f0; /* Background color of the rectangle */
                margin-top: 50px; /* Add margin-top to move the rectangle down */
            }
            .brectangle{
                width: 100%; /* Width of the rectangle */
                height: 250px; /* Height of the rectangle */
                background-color: #c7c0a978; /* Background color of the rectangle */
                margin-top: 450px; /* Add margin-top to move the rectangle down */
                text-align: center;
            }
            h1 {text-align: center;
                font-size: 34px;
                margin-top: 50px;
            }
            .right {float: right}
            .down {margin-top: 150px;}

            .brectangle {
                background-color: #c7c0a987; /* Blue background color */
                padding: 20px; /* Add padding to create space around the content */
                text-align: center; /* Center align the content */
            }
            .button {
                background-color: #99C1D6; /* White background color for the button */
                color: #ffffff; /* Blue text color for the button */
                border: none; /* Remove button border */
                padding: 10px 20px; /* Add padding to the button */
                font-size: 16px; /* Set font size */
                border-radius: 5px; /* Add rounded corners to the button */
                cursor: pointer; /* Change cursor to pointer on hover */
                transition: background-color 0.3s, color 0.3s; /* Add smooth transition for hover effect */
                text-decoration: none; /* Remove default link underline */
            }
            .button:hover {
                background-color: #ffffff; /* Darker blue background color on hover */
                color: #99C1D6; /* White text color on hover */
            }

        </style>
    </head>

    <body>
        <!-- your elements here -->
        <header>

            <div class="wrectangle">
            {% if not current_user.is_authenticated %}
            <div class="button-container right">
                <a href="{{url_for('auth.login')}}" class="button">Log in/Sign up (Clinical)</a>
            </div>

            <div class="button-container right">
                <a href="{{url_for('auth.login_patient')}}" class="button">Log in/Sign up (Patient)</a>
            </div>

            
            {% else %}
            

            <div class="button-container right">
                <a href="{{url_for('auth.logout')}}" class="button">Logout</a>
            </div>

            {% if current_user.role == 'hospital' %}
            <div class="button-container right">
                <a href="{{url_for('main.hospital_dashboard_View')}}" class="button">Dashboard</a>
            </div>
            {% else %}
            <div class="button-container right">
                <a href="{{url_for('main.patient_dashboard_View')}}" class="button">Dashboard</a>
            </div>
            
            {% endif %}
            {% endif %}
            <img src="{{ url_for('static', filename='images/logo.png')}}" alt="visionfit logo"  height="60px" width="60px"/>
            </div>
        </header>
        {% include "includes/messages.html" %}

            <div class="brectangle button-container">
            <h1>Early Detection To Diabetic Retinopathy!</h1>
            <a href="{{url_for('auth.sign_up_patient')}}" class="button">Book an Appointment</a>
            </div>

    </body>
</html>

final_updated/website/templates/signupH.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Signup</title>
    <style>
        body{
            background-color: #f9f9f9;
        }
        .container {
            position: relative;
            width: 450px;
            margin: 20px;
            padding: 20px;
            background-color: #ffffff;
            border-radius: 10px;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
            float: left; /* Move container to the left */
        }
        .background-image {
            position: absolute;
            top: 0;
            right: 0;
            bottom: 0;
            left: 68%; /* Move background image to the right */
            background-image: url('signup.jpeg');
            background-size: contain;
            z-index: -1; /* Ensure background image is behind other content */
        }
        h1 {
            text-align: center;
            color: #333;
        }
        .signup-form {
            display: flex;
            flex-direction: column;
        }
        .signup-form input {
            margin-bottom: 20px;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
            font-size: 16px;
        }
        .signup-form button {
            padding: 10px;
            border: none;
            border-radius: 4px;
            font-size: 16px;
            cursor: pointer;
            background-color: #99C1D6;
            color: #fff;
        }
        .signup-form button:hover {
            background-color: #0056b3;
        }
        .signup-form .social-login {
            margin-top: 20px;
            text-align: center;
        }
        .signup-form .social-login button {
            margin-top: 10px;
            background-color: #99C1D6; /* Facebook blue */
        }
        .signup-form .social-login button.google {
            background-color: #db4437; /* Google red */
        }
        .center{
            text-align: center;
        }
        h2{
            color: #a09e9e;
            font-size: medium;
        }
        h3{
            color: black;
            font-size: medium;
            font-family:Arial, Helvetica, sans-serif;
        }
        .button {
            background-color: #99C1D6; /* White background color for the button */
            color: #ffffff; /* Blue text color for the button */
            border: none; /* Remove button border */
            padding: 10px 20px; /* Add padding to the button */
            font-size: 16px; /* Set font size */
            border-radius: 5px; /* Add rounded corners to the button */
            cursor: pointer; /* Change cursor to pointer on hover */
            transition: background-color 0.3s, color 0.3s; /* Add smooth transition for hover effect */
            text-decoration: none; /* Remove default link underline */
            text-align: center;
        }
        .button:hover {
            background-color: #ffffff; /* Darker blue background color on hover */
            color: #99C1D6; /* White text color on hover */
        }
    </style>
</head>

<body>
    {% include "includes/messages.html" %}
    <div class="container">
        <h1>Sign up</h1>
        <h3>Already have an Account <a href="{{url_for('auth.login')}}"> Login</a></h3>
        <form class="signup-form" action="{{url_for('auth.sign_up')}}" method="POST">
            <h2>Full Name</h2>
            <input type="text" placeholder="Enter your Full Name" name="name" required>
            <h2>Email Address</h2>
            <input type="email" placeholder="Enter your Email Address" name="email" required>
            <h2>Password</h2>
            <input type="password" placeholder="Create your Password" name="password" required>
            <input type="submit" value="Create Account" class="button">
        </form>
        <div class="social-login center">
            <p>------ Or sign up using ------</p>
            <button class="google">Sign Up with Google</button>
            <button class="facebook">Sign Up with Facebook</button>
        </div>
    </div>
    <div class="background-image"></div> <!-- Background image -->
</body>
</html>

final_updated/website/templates/signupP.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Signup</title>
    <style>
        body{
            background-color: #f9f9f9;
        }
        .container {
            position: relative;
            width: 450px;
            margin: 20px;
            padding: 20px;
            background-color: #ffffff;
            border-radius: 10px;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
            float: left; /* Move container to the left */
        }
        .background-image {
            position: absolute;
            top: 0;
            right: 0;
            bottom: 0;
            left: 68%; /* Move background image to the right */
            background-image: url('signup.jpeg');
            background-size: contain;
            z-index: -1; /* Ensure background image is behind other content */
        }
        h1 {
            text-align: center;
            color: #333;
        }
        .signup-form {
            display: flex;
            flex-direction: column;
        }
        .signup-form input {
            margin-bottom: 20px;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
            font-size: 16px;
        }
        .signup-form button {
            padding: 10px;
            border: none;
            border-radius: 4px;
            font-size: 16px;
            cursor: pointer;
            background-color: #99C1D6;
            color: #fff;
        }
        .signup-form button:hover {
            background-color: #0056b3;
        }
        .signup-form .social-login {
            margin-top: 20px;
            text-align: center;
        }
        .signup-form .social-login button {
            margin-top: 10px;
            background-color: #99C1D6; /* Facebook blue */
        }
        .signup-form .social-login button.google {
            background-color: #db4437; /* Google red */
        }
        .center{
            text-align: center;
        }
        h2{
            color: #a09e9e;
            font-size: medium;
        }
        h3{
            color: black;
            font-size: medium;
            font-family:Arial, Helvetica, sans-serif;
        }
        .button {
            background-color: #99C1D6; /* White background color for the button */
            color: #ffffff; /* Blue text color for the button */
            border: none; /* Remove button border */
            padding: 10px 20px; /* Add padding to the button */
            font-size: 16px; /* Set font size */
            border-radius: 5px; /* Add rounded corners to the button */
            cursor: pointer; /* Change cursor to pointer on hover */
            transition: background-color 0.3s, color 0.3s; /* Add smooth transition for hover effect */
            text-decoration: none; /* Remove default link underline */
            text-align: center;
        }
        .button:hover {
            background-color: #ffffff; /* Darker blue background color on hover */
            color: #99C1D6; /* White text color on hover */
        }
    </style>
</head>

<body>
    {% include "includes/messages.html" %}
    <div class="container">
        <h1>Sign up</h1>
        <h3>Already have an Account <a href="{{url_for('auth.login_patient')}}"> Login</a></h3>
        <form class="signup-form" action="{{url_for('auth.sign_up_patient')}}" method="POST">
            <h2>Full Name</h2>
            <input type="text" placeholder="Enter your Full Name" name="name" required>
            <h2>Email Address</h2>
            <input type="email" placeholder="Enter your Email Address" name="email" required>
            <h2>Password</h2>
            <input type="password" placeholder="Create your Password" name="password" required>
            <input type="submit" value="Create Account" class="button">
        </form>
        <div class="social-login center">
            <p>------ Or sign up using ------</p>
            <button class="google">Sign Up with Google</button>
            <button class="facebook">Sign Up with Facebook</button>
        </div>
    </div>
    <div class="background-image"></div> <!-- Background image -->
</body>
</html>